---
title: Stone Monkey Studios
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: stonemonkeygames@gmail.com
description: 'Write an awesome description for your new site here, Stone Monkey. You
  can edit this line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

'
baseurl: ''
url: ''
owner: Ryan Nohr
facebook_username: 
twitter_username: 
github_username: 
address:
- line: 
- line: 
telephone: 
copyright: 2017
google_api_key: 
markdown: kramdown
