# Site settings
title: Test Title
email: stonemonkeygames@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here, Stone Monkey. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Ryan Nohr
email: stonemonkeygames@gmail.com
facebook_username: StoneMonkeyStudios
twitter_username: StoneMonkeyMen
github_username: 
address:
  - line: 
  - line:
  # Feel free to add more lines here 
telephone:
copyright: 2017

# API settings
google_api_key:

# Build settings
markdown: kramdown